app/views/admin.py
# -*-utf-8-*-
import oss2,io
from flask import Blueprint,request,render_template,session,redirect
from app.models import Admin,db,Goods
from app.common.argon2hash import argon2hasher
from app.common.authen import valid_admin,redis_client,protect_user_login,is_login
from uuid import  uuid4
from app import config
import urllib


adminapp = Blueprint('admin',__name__,url_prefix='/admin')

@adminapp.route('/register',methods=["GET","POST"])
def register():
    if request.method == "POST":
        #注册逻辑
        username = request.form.get('username')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        if password != confirm_password:
            return '两次密码不一致，重新注册'
        try:
            password_hash = argon2hasher(password)
            admin = Admin(username=username, password=password_hash)
            db.session.add(admin)
            db.session.commit()
            return "注册成功"
        except Exception as e:
            return "已存在该用户"
            db.session.rollback()
            raise e
        else:
            return "两次密码不一致，重新注册"

    return render_template("/admin/register.html")


@adminapp.route('/login',methods=["GET","POST"])
def login():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')
        result = valid_admin(username,password)
        if result is True:
            session['username'] = username
            return "恭喜你，登陆成功"
        else:
            return "登录失败"

    return render_template('admin/login.html')

@adminapp.route('/add_admin',methods=['GET','POST'])
@is_login
def add_admin():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')
        password_hash = argon2hasher(password)
        commit_csrf_token = request.form.get('csrf_token')
        if commit_csrf_token == redis_client.get(session['username']).decode('utf-8'):
            admin = Admin(username=username, password=password_hash)
            db.session.add(admin)
            db.session.commit()
            return "添加用户成功"
        else:
            return "CSRF TOKNE校验失败，无法添加用户"

    username = session['username']
    csrf_token = str(uuid4())
    redis_client.setex(username,600,csrf_token)
    return render_template('admin/add_admin.html',csrf_token=csrf_token)


@adminapp.route('/home',methods=['GET'])
@is_login
def home():
    return render_template('admin/home.html')


@adminapp.route('/admin_list',methods=['GET'])
@is_login
def admin_list():
    admin_list = db.session.query(Admin).all()
    return render_template('admin/admin_list.html',admin_list=admin_list)

@adminapp.route('/add_goods',methods=['POST','GET'])
@is_login
def add_goods():
    if request.method == "POST":
        goodsname = request.form.get('goodsname')
        category = request.form.get('category')
        mainimg = request.form.get('mainimg')
        content = request.form.get('content')
        sku = request.form.get('sku')
        price = request.form.get('price')

        try:
            db.session.add(Goods(goodsname=goodsname,category=category,mainimg=mainimg,content=content,sku=sku,price=price))
            db.session.commit()
            return "成功添加商品"
        except Exception as e:
            return "添加商品失败" + str(e)
    return render_template('admin/goods_add.html')

@adminapp.route('/goods_list',methods=['GET'])
@is_login
def goods_list():
    goods_list = db.session.query(Goods).all()
    return render_template('admin/goods_list.html',goods_list=goods_list)

@adminapp.route('/batch_goods',methods=['GET','POST'])
@is_login
def batch_goods():
    if request.method == "POST":
        batchfile = request.form.get('batchfile')

        print(urllib.request.urlopen(batchfile).read())
        goods_lists = urllib.request.urlopen(batchfile).read().decode('utf-8') #ssrf
        # goods_lists = requests.get(batchfile).content.decode('utf-8')
        try:
            content = goods_lists.split('\r\n')
            num = len(content)
            for i in range(1,num+1):
                if i<num+1:
                    items = content[i].split(',')
                    for row in items:
                        goods = Goods(
                            goodsname=row[0],
                            category=row[1],
                            mainimg=row[2],
                            content=row[3],
                            sku=int(row[4]),
                            price=float(row[5])
                        )

                        db.session.add(goods)
            db.session.commit()
            return content
        except:
            return content
    return render_template('admin/batch_goods.html')

@adminapp.route('/upload_goodsfile',methods=['POST'])
@is_login
def upload_goodsfile():
    ak = config.ossak
    sk = config.osssk
    auth = oss2.Auth(ak,sk)
    endpoint = "https://oss-cn-beijing.aliyuncs.com"
    bucket = oss2.Bucket(auth,endpoint,'m1nzhi')
    upload_file = request.files.get('file')
    upload_file_name = str(uuid4())+'.csv'
    upload_result = bucket.put_object(upload_file_name,upload_file)
    if upload_result.status == 200:
        file_url = bucket.sign_url('GET',upload_file_name,600)
        print(file_url)
        return {"fileUrl":file_url}
    else:
        return {"code":400,"msg":"上传失败"}

app/views/order.py
from flask import Blueprint,session,request,jsonify,render_template
from app.models import User,db,Goods,Order
from app.common.authen import user_is_login
from uuid import uuid4
from datetime import datetime
from app.common.lib import query_order


orderapp = Blueprint('order',__name__,url_prefix='/order')

@orderapp.route('/',methods=['GET','POST'])
@user_is_login
def index():
    user_id = session.get('user_id')
    if request.method == "POST":
        data = request.json
        addressid = data.get('address')
        goodsid = data.get('goods')
        randomuid = str(uuid4())
        randomuid_list = randomuid.split('-')
        order_id = ''.join(randomuid_list)
        generatetime = datetime.now()
        order = Order(id=order_id,generatetime=generatetime,user_id=user_id,goods_id=goodsid,payment_method="",address_id=addressid)
        try:
            db.session.add(order)
            db.session.commit()
            return jsonify({"code":201,"order_id":order_id})
        except:
            return jsonify({"code":501,"msg":"error"})

    goodsid = request.args.get('goodsid')
    goods = db.session.query(Goods).filter_by(id=goodsid).first()
    print(goods)
    user = db.session.query(User).filter_by(id=user_id).first()
    addresslist = user.addresses
    return render_template('/user/order.html',goods=goods,addresses=addresslist)


@orderapp.route('/list',methods=["GET","POST"])
@user_is_login
def orderlist():
    orders = Order.query.filter_by(user_id=session.get('user_id')).all()
    orderinfos = [{"goods":order.goods.goodsname,"price":order.goods.price,"orderid":order.id,"orderstatus":order.status,"time":order.generatetime} for order in orders]
    return render_template("/user/orderlist.html",orders=orderinfos)


@orderapp.route('/detail',methods=["GET"])
@user_is_login
def orderdetail():
    if request.args.get('orderid'):
        orderid = request.args.get('orderid')
        data = query_order(orderid)
        orderinfo = data[0]
        if orderinfo:
            order = {
                "orderid":orderinfo[0],
                "generatetime":orderinfo[1],
                "orderstatus":orderinfo[2],
                "payment":orderinfo[3],
                "receiver":orderinfo[4],
                "goodsname":orderinfo[5],
                "phone":orderinfo[6],
                "addressname":orderinfo[7]
            }
            return render_template("/user/orderdetail.html",order=order)
        else:
            return render_template('/user/orderdetail.html')
    else:
        return "参数错误"

@orderapp.route('/refund/<order_id>',methods=['GET','POST'])
@user_is_login
def refund(order_id):
    try:
        order = Order.query.get(order_id)
        if order.status != str(3):
            order.status = str(3)
            db.session.commit()
            return jsonify({"code":200,"msg":"成功发起退款"})
        return jsonify({"code":500,"msg":"已在退款中，等待商家确认退款"})
    except:
        db.session.rollback()
        return "退款失败"

@orderapp.route('/payment/<order_id>',methods=['GET','POST'])
@user_is_login
def payment(order_id):
    order = Order.query.get(order_id)
    user = User.query.filter_by(id=order.user_id).first()
    goods = Goods.query.get(order.goods_id)
    if request.method == "POST":
        payment_method = request.form.get('payment_method')
        balance = user.balance
       # goodsid = order.goods_id
        order.payment_method = payment_method
        if payment_method == "balance":
            if balance < goods.price:
                return "余额不足"
            user.balance = balance - goods.price
            order.status = "1"
            goods.sku = goods.sku-1
            db.session.commit()
            return "支付成功！订单ID: {}".format(order_id)
        else:
            return "暂不支持该方式支付"
    if order:
        return render_template("/user/payment.html",order=order,user=user,goods=goods)
    else:
        return "订单不存在"

app/views/user.py
from flask import Blueprint,url_for,request,render_template,current_app,session,redirect,flash
from app.models import User,db,Address
from app.common.argon2hash import argon2hasher
from app.common.authen import valid_user,redis_client,protect_user_login,vaild_email_phone,user_is_login
from uuid import uuid4
from flask_mail import Message


userapp = Blueprint('user',__name__,url_prefix='/user')


@userapp.route('/register',methods=["GET","POST"])
def register():
    if request.method == "POST":
        #注册逻辑
        phone = request.form.get('phone')
        email = request.form.get('email')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        if password != confirm_password:
            return '两次密码不一致，重新注册'
        try:
            password_hash = argon2hasher(password)
            user = User(phone=phone, email=email, password=password_hash)
            db.session.add(user)
            db.session.commit()
            flash('注册成功，请登录！', 'success')
            return redirect('/user/login')
        except Exception as e:
            print(str(e))
            return "已存在该用户"
            db.session.rollback()
            raise e

    return render_template("/user/register.html")

@userapp.route('/login',methods=["GET","POST"])
def login():
    if request.method == "POST":
        phone = request.form.get('phone')
        password = request.form.get('password')
        lock_msg = protect_user_login(phone)
        if lock_msg:
            return lock_msg

        result = valid_user(phone,password)
        if result is True:
            user = User.query.filter_by(phone=phone).first()
            session['user_id'] = user.id
            # session['username'] = user.phone
            return redirect('/')
        elif result is False:
            lockout_time = 60
            current_round = redis_client.get(f'current_round_{phone}')
            failed_attempts_key = f"attempts_{phone}_round_{current_round}"
            if redis_client.exists(failed_attempts_key):
                redis_client.incr(failed_attempts_key)
            else:
                redis_client.setex(failed_attempts_key,lockout_time,1)
            return "登陆失败"

    return render_template('user/login.html')

@userapp.route('/fotgotpassword',methods=["POST","GET"])
def forgot_passowrd():
    if request.method == "POST":
        email = request.form.get('email')
        phone = request.form.get('phone')
        if vaild_email_phone(email,phone):
            randomuid = str(uuid4())
            redis_client.setex(randomuid,600,email)
            url = f"/user/resetpassword/{randomuid}"
            host = request.host

            reset_url = f"http://{host}{url}"
            resetpassword_email = f"请点击一下链接进行密码重置：<a href='{reset_url}'>{reset_url}</a>, 有效期10分钟"
            message = Message(recipients=[email],subject="hackme重置密码")
            message.html =  resetpassword_email
            mail = current_app.extensions['mail']
            mail.send(message)
            return "密码重置链接已发送至您的邮箱，请点击邮箱中的链接进行密码重置"

        else:
            return "邮箱和用户名验证未通过"
    return render_template('user/forgotpassword.html')

@userapp.route('/resetpassword/<string:randomuid>',methods=["POST","GET"])
def reset_password(randomuid):
    # email = redis_client.get(randomuid)
    if request.method == "GET":
        if redis_client.exists(randomuid):
            email = redis_client.get(randomuid).decode('utf-8')
            return render_template('user/resetpassword.html',email=email,randomuid=randomuid)
        else:
            return render_template('user/resetpassword.html')
    else:
        email = request.form.get('email')
        password = request.form.get('password')
        password1 = request.form.get('confirm_password')
        if redis_client.exists(randomuid):
            redis_email = redis_client.get(randomuid).decode('utf-8')
            print(redis_email,email)
            if email == redis_email:
                if password!=password1:
                    return "两次输入的密码不一样，请检查"
                else:
                    password_hash = argon2hasher(password)
                    User.query.filter_by(email=email).update({"password":password_hash})
                    db.session.commit()

                    return "密码重置成功"
            else:
                return "您没有权限重置该账号密码"
        else:
            return "重置密码链接失效，请重新回到忘记密码页面进行操作"


@userapp.route('/address/add',methods=['GET','POST'])
@user_is_login
def address_add():
    if request.method == "POST":
        phone = request.form.get('phone')
        receiver = request.form.get('receiver')
        addressname = request.form.get('addressname')
        user_phone = session.get('phone')
        user = User.query.filter_by(phone=user_phone).first()
        user_id = user.id
        address = Address(receiver=receiver,phone=phone,addressname=addressname,user_id=user_id)
        db.session.add(address)
        try:
            db.session.commit()
            return redirect(url_for('user.addresslist'))
        except Exception as e:
            db.session.rollback()
            return str(e)

    return render_template('/user/address_add.html')

@userapp.route('/address/list',methods=['GET','POST'])
@user_is_login
def addresslist():
    addresses = Address.query.filter_by(user_id=session.get('user_id')).all()
    return render_template('/user/addresslist.html',addresses=addresses)


@userapp.route('/address/detail',methods=['GET','POST'])
@user_is_login
def addressdetail():
    if request.args.get('id'):
        address_id = request.args.get('id')
        address = Address.query.filter_by(id=address_id).first()
    return render_template('/user/addressdetail.html',address=address)


@userapp.route('/address/update/<id>',methods=['GET','POST'])
@user_is_login
def addressupdate(id):
    address = db.session.query(Address).filter_by(id=id).first()
    if request.method == "POST":
        receiver = request.form.get('receiver')
        addressname = request.form.get('addressname')
        phone = request.form.get('phone')
        try:
            db.session.query(Address).filter_by(id=id).update({"receiver":receiver,"addressname":addressname,"phone":phone})
            db.session.commit()
            return "更新地址成功"
        except:
            db.session.rollback()
            return "更新失败"
    return render_template('/user/addressupdate.html',address=address)

@userapp.route('/center',methods=['GET'])
@user_is_login
def center():
    return {"user":session.get('user_id')}


@userapp.route('/logout')
def logout():
    # 清除用户会话
    session.pop('user_id', None)
    session.pop('username', None)

    return redirect('/')

templates/user/address_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">
    <title>添加收货信息</title>
</head>
<body>
<form style="width: 600px; margin:100px auto" action="/user/address/add" method="post">
  <div class="mb-3">
    <label class="form-label">手机号</label>
    <input type="text" class="form-control" name="phone">
  </div>
  <div class="mb-3">
    <label class="form-label">收件人</label>
    <input type="text" class="form-control" name="receiver">
  </div>
  <div class="mb-3">
    <label class="form-label">收件地址</label>
    <input type="text" class="form-control" name="addressname">
  </div>
  <button type="submit" class="btn btn-primary">添加地址</button>
</form>
</body>
</html>

templates/user/addressdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">
    <title>我的订单</title>
</head>
<body>
    <p>收货人：{{ address.receiver }}</p>
    <p>地址：{{ address.addressname }}</p>
    <p>phone: {{ address.phone }}</p>
</body>

</html>

templates/user/addresslist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">
    <title>收货人信息列表</title>
</head>
<div class="container">
    <h4>我的地址</h4>
</div>
{% for address in addresses %}
<div class="card" style="width: 18rem; margin-top:10px">
  <div class="card-body">
      <h5>收件人：{{ address.receiver }}</h5>
      <p>手机号：{{ address.phone }}</p>
      <p>地址：{{ address.addressname }}</p>
      <a href="#" class="card-link">修改</a>
        <a href="#" class="card-link">删除</a>
  </div>

{% endfor %}

templates/user/addressupdate.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>update adderss</title>
</head>
<body>
  <form action="{{ url_for('user.addressupdate', id=address.id) }}" method="post">
    <input type="text" value="{{ address.receiver }}" name="receiver">
      <input type="text" value="{{ address.addressname }}" name="addressname">
      <input type="text" value="{{  address.phone }}" name="phone">
        <button type="submit" class="btn btn-primary">提交更新</button>
  </form>
</body>
</html>

templates/user/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
  <!-- Stack the columns on mobile by making one full-width and the other half-width -->
   <div class="row">
        <nav class="col-md-4 col-lg-2 d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li>
                    <a class="nav-item">
                        <a href="{{ url_for('admin.add_admin') }}">添加管理员</a>
                    </li>
                     <li>
                    <a class="nav-item">
                        <a href="{{ url_for('admin.admin_list') }}">后台用户列表</a>
                    </li>
                   <li>
                    <a class="nav-item">
                        <a href="{{ url_for('admin.goods_list') }}">商品列表</a>
                    </li>
                  <li>
                    <a class="nav-item">
                        <a href="{{ url_for('admin.add_goods') }}">添加商品</a>
                    </li>
                </ul>
            </div>
        </nav>
        <main role="main" class="col-md-8 ml-sm-auto col-lg-10 px-4">
            {% block content %}{% endblock %}
        </main>
   </div>

</body>
</html>

templates/user/forgotpassword.html
<html>
 <head>


     <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">
 </head>

<form style="width: 600px; margin:100px auto" action="/user/fotgotpassword" method="post">
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">邮箱</label>
    <input type="text" class="form-control" id="exampleInputPassword1" name="email">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">用户名</label>
    <input type="text" class="form-control" id="exampleInputPassword1" name="phone">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</html>

templates/user/login.html
<html>
 <head>
     <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">
 </head>
 {% with messages = get_flashed_messages(with_categories=true) %}
 {% if messages %}
   {% for category, message in messages %}
     <div class="alert alert-{{ category }}">
       {{ message }}
     </div>
   {% endfor %}
 {% endif %}
{% endwith %}
<form style="width: 600px; margin:100px auto" action="/user/login" method="post">
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">手机号</label>
    <input type="text" class="form-control" id="exampleInputPassword1" name="phone">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">密码</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>

</form>

</html>

templates/user/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">
    <title>下单页面</title>
</head>
<body>

<div class="container mt-5">
    <h2>确认订单</h2>

    <!-- 商品信息 -->
    <div class="card mb-4">
        <div class="card-header">
            商品信息
        </div>
        <div class="card-body" id="product-details" data-product-id="{{ goods.id }}">
            <h5 class="card-title">{{ goods.goodsname }}</h5>
            <img src={{ goods.mainimg }} class="card-img-top">
            <p class="card-text">价格：{{ goods.price }}</p>
        </div>
    </div>

<div class="container text-center" id="addressCards">
  <div class="row">
      {% for address in addresses %}
    <div class="col">
       <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ address.receiver }}</h5>
                <p class="card-text">{{ address.addressname}}</p>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="selectedAddress" id="addressRadio" value="{{ address.id }}">
                </div>
            </div>
       </div>
    </div>
      {% endfor %}

  </div>
</div>


    <button type="button" class="btn btn-primary" onclick="commitorder()">提交订单</button>
</div>


<script>
<!--    function selectAddress(address){-->
<!--        console.log(address);-->
<!--    }-->
    function commitorder(){
        var selectedAddress = $("input[name='selectedAddress']:checked").val();
        var productId = document.getElementById('product-details').dataset.productId;
        var orderInfo = {
            address: selectedAddress,
            goods: productId
        };
        $.ajax({
            type: 'POST',
            url: '/order',
            contentType: 'application/json',
            data: JSON.stringify(orderInfo),
            success: function(response) {
                console.log(response.order_id);
                window.location.href = '/order/payment/'+response.order_id;
            },
            error: function(error){
                //处理错误
                alert('error');
            }
        });
    }
</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

templates/user/orderdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">
    <title>我的订单</title>
</head>

<p>订单id: {{ order.orderid }}</p>
<p>订单生成时间: {{ order.generatetime }}</p>
<p>订单状态：{{ order.orderstatus }}</p>
<p>支付方式：{{ order.payment }}</p>
<p>商品：{{ order.goodsname }}</p>
<p>收货人：{{ order.receiver }}, 收货人电话：{{ order.phone }}， 收货地址: {{ order.addressname }}</p>
<a href="{{ url_for('user.refund', order_id=order.orderid) }}">退款</a>
</html>

templates/user/orderlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">
    <title>我的订单</title>
</head>

<body>
 {% for order in orders %}
<div class="card" style="width: 18rem; margin-top:10px">

  <div class="card-body" >
      <h6 class="card-title">订单ID：{{ order.orderid }}</h6>
      <h6 class="card-subtitle mb-2 text-muted">{{ order.time }}</h6>
      <p>商品：{{ order.goods }}<p>
       <p>订单价格：{{ order.price }}<p>
      <p>订单状态：
      {% if order.orderstatus is none %}
      未支付
      {% elif order.orderstatus == "1" %}
      已支付
      {% else %}
      订单失效
      {% endif %}
      <p>
         <a href="/user/order/detail?orderid={{ order.orderid }}" class="card-link">订单详情</a>
  </div>

</div>
   {% endfor %}


</body>

templates/user/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>支付页面</title>
</head>
<body>

  <h1>支付页面</h1>
  <p>订单ID: {{ order.id }}</p>
  <p>订单金额：{{ goods.price }}</p>
  <p>用户余额: ${{ user.balance }}</p>
  <form action="{{ url_for('order.payment', order_id=order.id) }}" method="post">
    <label for="payment_method">选择支付方式：</label>
    <select id="payment_method" name="payment_method" required>
      <option value="balance">余额支付</option>
      <option value="wechat">微信支付</option>
      <!-- 其他支付方式 -->
    </select>
    <br>
    <button type="submit">支付</button>
  </form>

</body>
</html>

templates/user/refund.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">
    <title>退款</title>
</head>

<body>
  <form action="{{ url_for('user.refund', order_id=order.id) }}" method="post">
<form action=""></form>
</body>
</html>

templates/user/register.html
<html>
 <head>


   <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">

 </head>

<form style="width: 600px; margin:100px auto" action="/user/register" method="post">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">手机号</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="phone">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">email</label>
    <input type="text" class="form-control" id="exampleInputPassword1" name="email">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">密码</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">确认密码</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="confirm_password">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</html>

templates/user/resetpassword.html
<html>
 <head>
<h2>重置密码</h2>
<p>请为{{ email }}设置密码</p>
     <link href={{ url_for('static',filename='css/bootstrap.min.css') }} rel="stylesheet">
 </head>

<form style="width: 600px; margin:100px auto" action="/user/resetpassword/{{ randomuid }}" method="post">
    <input type="hidden"  class="form-control" id="exampleInputPassword1" name="email" value="{{ email }}">
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">设置密码</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
      <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">确认设置密码</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="confirm_password">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</html>